services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: mica
    environment:
      - STGUIADDRESS=0.0.0.0:8384 # empty means defaults to 0.0.0.0:8384
    volumes:
      - /srv/syncthing/config:/var/syncthing
    network_mode: host
    restart: unless-stopped
