services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    ports:
      - 445:445
    volumes:
      - /srv/services/samba/smb.conf:/etc/samba/smb.conf
      - /srv/services/samba/users.conf:/etc/samba/users.conf
    restart: unless-stopped
