services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    environment:
      - NAME=nimbo
      - USER=samba
      - PASS=${PASS}
    ports:
      - 445:445
    volumes:
      - /srv/nimbo:/shared
    restart: unless-stopped
